//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  badge_lw: Badge_Lw;
  badge_lwConnection: Badge_LwConnection;
  firmware: Firmware;
  firmwareConnection: FirmwareConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBadge_LwArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBadge_LwConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<Badge_LwFilter>;
};


export type QueryFirmwareArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFirmwareConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FirmwareFilter>;
};

export type DocumentFilter = {
  badge_lw?: InputMaybe<Badge_LwFilter>;
  firmware?: InputMaybe<FirmwareFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Badge_Lw | Firmware | Folder;

export type Badge_Lw = Node & Document & {
  __typename?: 'Badge_lw';
  title: Scalars['String']['output'];
  sidebar_position?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Badge_LwFilter = {
  title?: InputMaybe<StringFilter>;
  sidebar_position?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type Badge_LwConnectionEdges = {
  __typename?: 'Badge_lwConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Badge_Lw>;
};

export type Badge_LwConnection = Connection & {
  __typename?: 'Badge_lwConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<Badge_LwConnectionEdges>>>;
};

export type Firmware = Node & Document & {
  __typename?: 'Firmware';
  title: Scalars['String']['output'];
  sidebar_position?: Maybe<Scalars['Float']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FirmwareFilter = {
  title?: InputMaybe<StringFilter>;
  sidebar_position?: InputMaybe<NumberFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type FirmwareConnectionEdges = {
  __typename?: 'FirmwareConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Firmware>;
};

export type FirmwareConnection = Connection & {
  __typename?: 'FirmwareConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FirmwareConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateBadge_lw: Badge_Lw;
  createBadge_lw: Badge_Lw;
  updateFirmware: Firmware;
  createFirmware: Firmware;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateBadge_LwArgs = {
  relativePath: Scalars['String']['input'];
  params: Badge_LwMutation;
};


export type MutationCreateBadge_LwArgs = {
  relativePath: Scalars['String']['input'];
  params: Badge_LwMutation;
};


export type MutationUpdateFirmwareArgs = {
  relativePath: Scalars['String']['input'];
  params: FirmwareMutation;
};


export type MutationCreateFirmwareArgs = {
  relativePath: Scalars['String']['input'];
  params: FirmwareMutation;
};

export type DocumentUpdateMutation = {
  badge_lw?: InputMaybe<Badge_LwMutation>;
  firmware?: InputMaybe<FirmwareMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  badge_lw?: InputMaybe<Badge_LwMutation>;
  firmware?: InputMaybe<FirmwareMutation>;
};

export type Badge_LwMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  sidebar_position?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type FirmwareMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  sidebar_position?: InputMaybe<Scalars['Float']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type Badge_LwFilter = {
  title?: StringFilter | null | undefined;
  sidebar_position?: NumberFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type FirmwareFilter = {
  title?: StringFilter | null | undefined;
  sidebar_position?: NumberFilter | null | undefined;
  body?: RichTextFilter | null | undefined;
};

export type Badge_LwPartsFragment = { __typename: 'Badge_lw', title: string, sidebar_position: number | null, body: any };

export type FirmwarePartsFragment = { __typename: 'Firmware', title: string, sidebar_position: number | null, body: any };

export type Badge_LwQueryVariables = Exact<{
  relativePath: string;
}>;


export type Badge_LwQuery = { badge_lw: { __typename: 'Badge_lw', id: string, title: string, sidebar_position: number | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type Badge_LwConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: Badge_LwFilter | null | undefined;
}>;


export type Badge_LwConnectionQuery = { badge_lwConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Badge_lw', id: string, title: string, sidebar_position: number | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FirmwareQueryVariables = Exact<{
  relativePath: string;
}>;


export type FirmwareQuery = { firmware: { __typename: 'Firmware', id: string, title: string, sidebar_position: number | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FirmwareConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: FirmwareFilter | null | undefined;
}>;


export type FirmwareConnectionQuery = { firmwareConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Firmware', id: string, title: string, sidebar_position: number | null, body: any, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const Badge_LwPartsFragmentDoc = gql`
    fragment Badge_lwParts on Badge_lw {
  __typename
  title
  sidebar_position
  body
}
    `;
export const FirmwarePartsFragmentDoc = gql`
    fragment FirmwareParts on Firmware {
  __typename
  title
  sidebar_position
  body
}
    `;
export const Badge_LwDocument = gql`
    query badge_lw($relativePath: String!) {
  badge_lw(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...Badge_lwParts
  }
}
    ${Badge_LwPartsFragmentDoc}`;
export const Badge_LwConnectionDocument = gql`
    query badge_lwConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: Badge_lwFilter) {
  badge_lwConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...Badge_lwParts
      }
    }
  }
}
    ${Badge_LwPartsFragmentDoc}`;
export const FirmwareDocument = gql`
    query firmware($relativePath: String!) {
  firmware(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FirmwareParts
  }
}
    ${FirmwarePartsFragmentDoc}`;
export const FirmwareConnectionDocument = gql`
    query firmwareConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FirmwareFilter) {
  firmwareConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FirmwareParts
      }
    }
  }
}
    ${FirmwarePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      badge_lw(variables: Badge_LwQueryVariables, options?: C): Promise<{data: Badge_LwQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Badge_LwQueryVariables, query: string}> {
        return requester<{data: Badge_LwQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Badge_LwQueryVariables, query: string}, Badge_LwQueryVariables>(Badge_LwDocument, variables, options);
      },
    badge_lwConnection(variables?: Badge_LwConnectionQueryVariables, options?: C): Promise<{data: Badge_LwConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Badge_LwConnectionQueryVariables, query: string}> {
        return requester<{data: Badge_LwConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: Badge_LwConnectionQueryVariables, query: string}, Badge_LwConnectionQueryVariables>(Badge_LwConnectionDocument, variables, options);
      },
    firmware(variables: FirmwareQueryVariables, options?: C): Promise<{data: FirmwareQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FirmwareQueryVariables, query: string}> {
        return requester<{data: FirmwareQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FirmwareQueryVariables, query: string}, FirmwareQueryVariables>(FirmwareDocument, variables, options);
      },
    firmwareConnection(variables?: FirmwareConnectionQueryVariables, options?: C): Promise<{data: FirmwareConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FirmwareConnectionQueryVariables, query: string}> {
        return requester<{data: FirmwareConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FirmwareConnectionQueryVariables, query: string}, FirmwareConnectionQueryVariables>(FirmwareConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  